# Generated by Django 5.2 on 2025-04-23 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 23, 23, 15, 46, 195345, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
