# Generated by Django 5.1.6 on 2025-03-27 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('Clock In', 'Clock In'), ('Clock Out', 'Clock Out')], max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OC.player')),
            ],
        ),
    ]
