# Generated by Django 5.2 on 2025-04-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clockrecord',
            name='total_hours',
        ),
        migrations.AlterField(
            model_name='clockrecord',
            name='clock_in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clockrecord',
            name='clock_out_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clockrecord',
            name='employee_name',
            field=models.CharField(max_length=255),
        ),
    ]
