# Generated by Django 5.2 on 2025-04-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OC', '0002_remove_clockrecord_total_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockrecord',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='clockrecord',
            name='clock_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clockrecord',
            name='clock_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clockrecord',
            name='employee_name',
            field=models.CharField(max_length=100),
        ),
    ]
