# Generated by Django 5.1.6 on 2025-02-17 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_start', models.DateField()),
                ('pay_end', models.DateField()),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calc_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
